kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tomcat-demo
  namespace: tomcat-demo
  labels:
    run: tomcat-demo
  annotations:
    openshift.io/host.generated: 'true'
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  to:
    kind: Service
    name: tomcat-demo
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
